- name: variables from inventory
  hosts: localhost
  tasks:
    - name: print information
      vars:
        timings: "07:15 AM IST"
      ansible.builtin.debug:
        msg: "Hi We are learning {{Course}}, by Trainer {{Trainer}} to learner {{Learner}}, Course duration is {{Duration}} and the timings are {{timings}}."