- name: Variables preference
  hosts: localhost
  vars:
    Wishes: "Morning from play variables"
  vars_prompt:
  - name: Wishes
    prompt: Enter the Wishes
    private: false
  tasks:
  - name: check performance
    ansible.builtin.debug:
      msg: "Hello, Good {{Wishes}}"


# 1. Arguments variable
# 2. Task variable
# 3. Variable files
#