- name: Variables preference
  hosts: localhost
  vars:
    Wishes: "Morning from play variables"
  vars_files:
  - vars.yaml
  vars_prompt:
  - names: Wishes
  - prompt: please enter wishes
  - private: false
  tasks:
  - name: check performance
    vars:
      Wishes: "Morning from task variables"
    ansible.builtin.debug:
      msg: "Hello, Good {{Wishes}}"
