- name: data types
  hosts: localhost
  vars:
    Course: Devops with AWS  #string
    Tools:   # list  (list starts with -)
    - Linux
    - Shell
    - Ansible
    Experience:  # map or dictionary (Map is like a key to value, Ex: Experience is a key and Devops - 3 is the value)
      Devops: 3  # number
      Aws: 2
      Docker: 1
    RealProject: True  #boolean
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Course: {{Course}}, Tools covered: {{Tools}}, Experience is: {{Experience}}, is Real Project {{RealProject}}"