- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{Course | default('Ansible')}}"

- name: Upper case
  hosts: localhost
  vars:
    greetings: "Hello good morning"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: "{{ greetings | upper }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1, 2, 3, 3, 4, 5, 5]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

- name: convert dictionary into items/list
  hosts: localhost
  vars:
    we_dict: # this is called as dictionary or map or key/value pairs
      Course: Ansible
      Trainer: Sivakumar
      Duration: 120 hours
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert {{we_dict}}"
  - name: after convert
    ansible.builtin.debug:
      msg: "After convert {{we_dict | dict2items}}"