- name: advance loops
  hosts: web
  become: yes
  tasks:
  - name: install and uninstall packages
    ansible.builtin.dnf:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'mysql', state: 'present'} #item
    - {name: 'nginx', state: 'absent'}
    - {name: 'postfix', state: 'absent'}
