- name: command module vs shell module
  hosts: localhost
  tasks:
  - name: Command module
    ansible.builtin.command: echo 'Hi, this is from command module' > /tmp/command.txt

  - name: shell module
    ansible.builtin.shell: echo 'Hi, this is from shell module' > /tmp/shell.txt