- name: variables from inventory
  hosts: localhost
  tasks:
    - name: print information
      ansible.builtin.debug:
        msg: >
          "Hi, we are learning {{Course}}, taught by Trainer {{Trainer}}.
          Course duration is {{Duration}}."
